### ISSUE TITLE
用官方的docker-compose demo直接运行后出现错误

### ISSUE THREAD

**Issue by levin222** [Elico-Corp/odoo-docker#127]
version: '3.3'
services:

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=strong_pg_superuser_password

  odoo:
    image: elicocorp/odoo:10.0
    command: start
    ports:
      - 127.0.0.1:8069:8069
    links:
      - postgres:db
    environment:
      - ODOO_ADMIN_PASSWD=strong_odoo_master_password
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=strong_pg_odoo_password
 用这个直接运行出现下面错误， 应该好似没有添加 odoo用户和role的缘故，应该要写在 compose配置文件里面比较合理吧

odoo_1      | 2019-03-16 15:15:25,889 54 INFO ? odoo.sql_db: Connection to the database failed
odoo_1      | 2019-03-16 15:15:25,891 54 INFO ? werkzeug: 172.23.0.1 - - [16/Mar/2019 15:15:25] "GET / HTTP/1.1" 500 -
odoo_1      | 2019-03-16 15:15:25,900 54 ERROR ? werkzeug: Error on request:
odoo_1      | Traceback (most recent call last):
odoo_1      |   File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
odoo_1      |     execute(self.server.app)
odoo_1      |   File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 193, in execute
odoo_1      |     application_iter = app(environ, start_response)
odoo_1      |   File "/opt/odoo/sources/odoo/odoo/service/server.py", line 260, in app
odoo_1      |     return self.app(e, s)
odoo_1      |   File "/opt/odoo/sources/odoo/odoo/service/wsgi_server.py", line 166, in application
odoo_1      |     return application_unproxied(environ, start_response)
odoo_1      |   File "/opt/odoo/sources/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
odoo_1      |     result = handler(environ, start_response)
odoo_1      |   File "/opt/odoo/sources/odoo/odoo/http.py", line 1319, in __call__
odoo_1      |     return self.dispatch(environ, start_response)
odoo_1      |   File "/opt/odoo/sources/odoo/odoo/http.py", line 1293, in __call__
odoo_1      |     return self.app(environ, start_wrapped)
odoo_1      |   File "/usr/local/lib/python3.5/dist-packages/werkzeug/wsgi.py", line 599, in __call__
odoo_1      |     return self.app(environ, start_response)
odoo_1      |   File "/opt/odoo/sources/odoo/odoo/http.py", line 1456, in dispatch
odoo_1      |     self.setup_db(httprequest)
odoo_1      |   File "/opt/odoo/sources/odoo/odoo/http.py", line 1388, in setup_db
odoo_1      |     httprequest.session.db = db_monodb(httprequest)
odoo_1      |   File "/opt/odoo/sources/odoo/odoo/http.py", line 1540, in db_monodb
odoo_1      |     dbs = db_list(True, httprequest)
odoo_1      |   File "/opt/odoo/sources/odoo/odoo/http.py", line 1507, in db_list
odoo_1      |     dbs = odoo.service.db.list_dbs(force)
odoo_1      |   File "/opt/odoo/sources/odoo/odoo/service/db.py", line 369, in list_dbs
odoo_1      |     with closing(db.cursor()) as cr:
odoo_1      |   File "/opt/odoo/sources/odoo/odoo/sql_db.py", line 637, in cursor
odoo_1      |     return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
odoo_1      |   File "/opt/odoo/sources/odoo/odoo/sql_db.py", line 178, in __init__
odoo_1      |     self._cnx = pool.borrow(dsn)
odoo_1      |   File "/opt/odoo/sources/odoo/odoo/sql_db.py", line 520, in _locked
odoo_1      |     return fun(self, *args, **kwargs)
odoo_1      |   File "/opt/odoo/sources/odoo/odoo/sql_db.py", line 588, in borrow
odoo_1      |     **connection_info)
odoo_1      |   File "/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py", line 130, in connect
odoo_1      |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
odoo_1      | psycopg2.OperationalError: FATAL:  role "odoo" does not exist

**Comment by elicoidal** [comment]
This looks incorrect:
> - POSTGRES_PASSWORD=strong_pg_superuser_password

should be 

- POSTGRES_PASSWORD=strong_pg_odoo_password

**Comment by levin222** [comment]
get it

**Comment by elicoidal** [comment]
If you have anything else, please do not hesitate to reopen this issues or open a new one.
